# Build the JAR file
FROM maven:3.8.4-openjdk-22-slim AS builder
COPY ./rest-api-server /usr/src/app
WORKDIR /usr/src/app
RUN mvn clean package

# Create the final image
FROM openjdk:22-jdk-slim
COPY --from=builder /usr/src/app/target/rest-api-server-0.0.1-SNAPSHOT.jar /usr/app/rest-api-server.jar
WORKDIR /usr/app
ENTRYPOINT ["java", "-jar", "rest-api-server.jar"]
